
temperatura_fahrenheit=0
temperatura_fahrenheit1=0
temperatura_fahrenheit2=0
temperatura_fahrenheit3=0
temperatura_fahrenheit4=0

if temperatura_fahrenheit > 85:
 print("la Temparatura corresponde al deporte de Natacion: ", temperatura_fahrenheit )
 
#return "Tenis" 
elif 70 < temperatura_fahrenheit1 <= 85:
  print("la Temparatura corresponde al deporte de Tenis: ", temperatura_fahrenheit1 )  
    
#return "Tenis"
elif 32 < temperatura_fahrenheit2 <= 70:
  print("la Temparatura corresponde al deporte de Tenis: ", temperatura_fahrenheit2 )
# return "Golf"
elif 10 < temperatura_fahrenheit3 <= 32:
  print("la Temparatura corresponde al deporte de Golf: ", temperatura_fahrenheit3 )
    #return "Esquí"
elif temperatura_fahrenheit4 <= 10:
  print("la Temparatura corresponde al deporte de Esqui: ", temperatura_fahrenheit4 )
#  return "Marcha"